# Generated by cucumber-sinatra. (2012-04-06 20:29:34 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/mock_inhalt.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MockInhalt

class MockInhaltWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MockInhaltWorld.new
end
